### ISSUE TITLE
Import of data causes database errors

### ISSUE THREAD

**Issue by linawolf** [sabbelasichon/bzga_beratungsstellensuche_essstoerungen#2]
Using this extension to import data On Typo3 9.5.21 I ran accross several errors for whitch you can finde my patches attached:

- Missing default values in the TCA definition led to errors on importing empty / null values in a strict database setting.

- Boolean values got misinterpreted as the are represented as strings of "0" or "1" in the xml import files.

- The Image Link converter did not propperly catch errors in case of unexpected mime types (yes indeed, some organizations did upload their logo as doc....)

- Also if the file is not an image getimagesizefromstring will fail completely

Furthermore due to a core bug which has no fix yet https://forge.typo3.org/issues/90063#change-431917 GeneralUtility::writeFileToTypo3tempDir always returns an error even if the file was successfully uploaded. Therefore I added as workaround a check weather the file was uploaded to prevent multiple uploads of the same image.  

Please find my changes in the attached patch file.

Greetings Lina

[[BUGFIX]_Workaround_Bug_https___forge_typo3_org_issues_90063#change-431917_[BUGFIX]_Import.zip](https://github.com/sabbelasichon/bzga_beratungsstellensuche_essstoerungen/files/5290827/BUGFIX._Workaround_Bug_https___forge_typo3_org_issues_90063.change-431917_.BUGFIX._Import.zip)

**Comment by sabbelasichon** [comment]
@linawolf Hi, thanks for your detailed report and your fixes. It would be really helpful, if you could create a Pull Request for every issue separately. Mabye i can help you to get started. Don´t hesitate to contact me.

**Comment by sabbelasichon** [comment]
@linawolf I am gonna close this issue, because all your changes are applied to in this repository: https://github.com/sabbelasichon/bzga_beratungsstellensuche/pull/7
